#include "database.hpp"
#include <sqlite3.h>
#include <stdexcept>
#include <sstream>
static void ck(int rc,sqlite3*d){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE)throw std::runtime_error(sqlite3_errmsg(d));}
Database::Database(const std::string&p){if(sqlite3_open(p.c_str(),&db_)!=SQLITE_OK)throw std::runtime_error(sqlite3_errmsg(db_));init();}
Database::~Database(){if(db_)sqlite3_close(db_);}
void Database::init(){const char*q="PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS devices(id INTEGER PRIMARY KEY,ip TEXT UNIQUE,sys_name TEXT,sys_descr TEXT,sys_object_id TEXT,sys_uptime TEXT,vendor TEXT,device_type TEXT,last_seen TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS interfaces(id INTEGER PRIMARY KEY,device_id INTEGER,if_index INTEGER,name TEXT,description TEXT,type TEXT,speed TEXT,admin_status TEXT,oper_status TEXT,FOREIGN KEY(device_id) REFERENCES devices(id));";char*e=nullptr;if(sqlite3_exec(db_,q,nullptr,nullptr,&e)!=SQLITE_OK){std::string x=e?e:"db error";sqlite3_free(e);throw std::runtime_error(x);}}
void Database::save(const Device&d){sqlite3_stmt*s=nullptr;ck(sqlite3_prepare_v2(db_,"INSERT INTO devices(ip,sys_name,sys_descr,sys_object_id,sys_uptime,vendor,device_type) VALUES(?,?,?,?,?,?,?) ON CONFLICT(ip) DO UPDATE SET sys_name=excluded.sys_name,sys_descr=excluded.sys_descr,sys_object_id=excluded.sys_object_id,sys_uptime=excluded.sys_uptime,vendor=excluded.vendor,device_type=excluded.device_type,last_seen=CURRENT_TIMESTAMP",-1,&s,nullptr),db_);const std::string a[]={d.ip,d.sysName,d.sysDescr,d.sysObjectId,d.sysUpTime,d.vendor,d.deviceType};for(int i=0;i<7;++i)sqlite3_bind_text(s,i+1,a[i].c_str(),-1,SQLITE_TRANSIENT);ck(sqlite3_step(s),db_);sqlite3_finalize(s);}
std::string Database::devicesJson()const{sqlite3_stmt*s=nullptr;sqlite3_prepare_v2(db_,"SELECT ip,sys_name,sys_descr,sys_object_id,sys_uptime,vendor,device_type,last_seen FROM devices ORDER BY ip",-1,&s,nullptr);std::ostringstream o;o<<"[";bool f=true;while(sqlite3_step(s)==SQLITE_ROW){if(!f)o<<",";f=false;o<<"{\"ip\":\""<<sqlite3_column_text(s,0)<<"\",\"sysName\":\""<<sqlite3_column_text(s,1)<<"\",\"sysDescr\":\""<<sqlite3_column_text(s,2)<<"\",\"sysObjectId\":\""<<sqlite3_column_text(s,3)<<"\",\"sysUpTime\":\""<<sqlite3_column_text(s,4)<<"\",\"vendor\":\""<<sqlite3_column_text(s,5)<<"\",\"deviceType\":\""<<sqlite3_column_text(s,6)<<"\",\"lastSeen\":\""<<sqlite3_column_text(s,7)<<"\"}";}o<<"]";sqlite3_finalize(s);return o.str();}
